---
abstract: 'Perl Couchbase Client'
author:
  - 'M. Nunberg <mnunberg@haskalah.org>'
build_requires:
  ExtUtils::MakeMaker: 0
configure_requires:
  Dir::Self: 0
dynamic_config: 1
generated_by: 'ExtUtils::MakeMaker version 6.62, CPAN::Meta::Converter version 2.112150'
license: perl
meta-spec:
  url: http://module-build.sourceforge.net/META-spec-v1.4.html
  version: 1.4
name: Couchbase-Client
no_index:
  directory:
    - t
    - inc
requires:
  Alien::Libevent: 0.001004
  Array::Assign: 0
  Class::XSAccessor: 1.11
  ExtUtils::H2PM: 0.08
  Log::Fu: 0.25
  POE: 1.312
  POE::Sugar::Attributes: 0.02
  Test::Class: 0.36
  Test::More: 0
version: 0.12_0
